name: dcp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.3
  - python=3.8.5
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alembic==1.6.5
    - amqp==5.0.6
    - autopep8==1.5.7
    - billiard==3.6.4.0
    - celery==5.1.2
    - click==7.1.2
    - click-didyoumean==0.0.3
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - flake8==3.9.2
    - flask==2.0.1
    - flask-cors==3.0.10
    - flask-migrate==3.0.1
    - flask-sqlalchemy==2.5.1
    - greenlet==1.1.0
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - kombu==5.1.0
    - mako==1.1.4
    - markupsafe==2.0.1
    - mccabe==0.6.1
    - numpy==1.20.3
    - pandas==1.2.5
    - pep8==1.7.1
    - prompt-toolkit==3.0.19
    - psycopg2==2.9.1
    - pycodestyle==2.7.0
    - pyflakes==2.3.1
    - pylsl==1.14.0
    - python-dateutil==2.8.1
    - python-dotenv==0.17.1
    - python-editor==1.0.4
    - pytz==2021.1
    - six==1.16.0
    - sqlalchemy==1.4.19
    - toml==0.10.2
    - vine==5.0.0
    - wcwidth==0.2.5
    - werkzeug==2.0.1
