"""Initial database design for CollectedData.

Revision ID: 100952a8ec0b
Revises: 
Create Date: 2022-01-16 12:02:04.877379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100952a8ec0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_instance')
    op.add_column('collected_data', sa.Column('collection_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('collected_data', sa.Column('config_id', sa.Integer(), nullable=False))
    op.add_column('collected_data', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_constraint('collected_data_collection_instance_id_fkey', 'collected_data', type_='foreignkey')
    op.create_foreign_key(None, 'collected_data', 'bci_config', ['config_id'], ['id'])
    op.drop_column('collected_data', 'collection_instance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collected_data', sa.Column('collection_instance_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'collected_data', type_='foreignkey')
    op.create_foreign_key('collected_data_collection_instance_id_fkey', 'collected_data', 'collection_instance', ['collection_instance_id'], ['id'])
    op.drop_column('collected_data', 'order')
    op.drop_column('collected_data', 'config_id')
    op.drop_column('collected_data', 'collection_time')
    op.create_table('collection_instance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collection_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['bci_config.id'], name='collection_instance_config_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_instance_pkey')
    )
    # ### end Alembic commands ###
