"""Update BCICollection model to add collect start and collect stop time.
Revision ID: 2657dc7f6992
Revises: 
Create Date: 2022-03-06 17:03:42.135172
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2657dc7f6992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bci_collection', sa.Column('collection_start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bci_collection', sa.Column('collection_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bci_collection', 'collection_end_time')
    op.drop_column('bci_collection', 'collection_start_time')
    # ### end Alembic commands ###