version: "3.8"

volumes:
    # volume to persist on local machine
    db_data_dev:

services:
    rabbitmq: 
        container_name: dcp_rabbitmq_dev
        image: rabbitmq:3-management
        hostname: ${DEV_MESSAGE_QUEUE_HOSTNAME}
        restart: always
        env_file:
            - .env
        environment: 
            - RABBITMQ_DEFAULT_USER=${DEV_RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${DEV_RABBITMQ_DEFAULT_PASSWORD}
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - default
    celery:
        container_name: dcp_celery_dev
        image: dcp_celery_dev:tag
        build:
            context: .
            dockerfile: docker/dev/celery/Dockerfile
        restart: always
        env_file: 
            - .env
        depends_on:
            - rabbitmq       
    db:
        image: postgres:12.2
        container_name: dcp_db_dev
        hostname: ${DB_HOSTNAME}
        env_file: 
            - .env 
        environment: 
            - POSTGRES_USER=${DEV_DB_USERNAME}
            - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
        restart: always
        volumes: # persist data beyond life of container 
            - db_data_dev:/var/lib/postgresql/data
        ports:
            - "${DEV_DB_PORT}:5432"
    app:
        image: dcp_app_dev:tag
        container_name: dcp_app_dev
        build:
            context: .
            dockerfile: docker/dev/app/Dockerfile
        command: ["flask", "run"]
        env_file:
            - .env
        # use host's network
        # network_mode: "host"
        # privileged: true
        ports:
            # - "1-65535:1-65535"
            - "5000:5000"
            - "16571-16604:16571-16604"
        depends_on:
            - db
            - rabbitmq
            - celery
        # devices: 
            # - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            # changes in current directory will be automatically reflected inside the container
            - .:/usr/src/dcp/backend
            # - /dev:/dev
            # - /dev/bus/usb:/dev/bus/usb
