version: "3.8"

services:
    app:
        container_name: open_bci
        image: openbci_test
        build:
            # network: host
            context: .
            dockerfile: docker/test/Dockerfile
        env_file:
            - .env
        # use host's network
        network_mode: "host"
        privileged: true
        # docker run --network host --privileged
        # ports:
            # - "1-65535:1-65535"
            # - "5000:5000"
            # - "16571-16604:16571-16604"
        # devices: 
        #     - "/dev/ttyUSB0:/dev/ttyUSB0"
        volumes:
            # changes in current directory will be automatically reflected inside the container
            - ".:/usr/src/dcp/backend"
            # - "/dev:/dev"
            # - /dev/bus/usb:/dev/bus/usb
        extra_hosts:
            - "host.docker.internal:host-gateway"
    # pingtest:
    #     image: alpine
    #     extra_hosts:
    #         host.docker.internal: host-gateway
