"""Initial migration for creating tables.

Revision ID: 12ed66ce6913
Revises: 
Create Date: 2021-07-01 02:04:50.862324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ed66ce6913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bci_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=50), nullable=False),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('is_stressful', sa.Boolean(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('youtube_url', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['bci_config.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collected_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_1', sa.Float(), nullable=True),
    sa.Column('channel_2', sa.Float(), nullable=True),
    sa.Column('channel_3', sa.Float(), nullable=True),
    sa.Column('channel_4', sa.Float(), nullable=True),
    sa.Column('channel_5', sa.Float(), nullable=True),
    sa.Column('channel_6', sa.Float(), nullable=True),
    sa.Column('channel_7', sa.Float(), nullable=True),
    sa.Column('channel_8', sa.Float(), nullable=True),
    sa.Column('is_subject_anxious', sa.Boolean(), nullable=True),
    sa.Column('collection_instance', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_instance'], ['collection_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collected_data')
    op.drop_table('collection_instance')
    op.drop_table('video')
    op.drop_table('bci_config')
    # ### end Alembic commands ###
