"""Rename collection_instance to collection_instance_id for Collected Data

Revision ID: 40d7f87884c5
Revises: 12ed66ce6913
Create Date: 2021-07-01 03:00:26.082401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d7f87884c5'
down_revision = '12ed66ce6913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collected_data', sa.Column('collection_instance_id', sa.Integer(), nullable=True))
    op.drop_constraint('collected_data_collection_instance_fkey', 'collected_data', type_='foreignkey')
    op.create_foreign_key(None, 'collected_data', 'collection_instance', ['collection_instance_id'], ['id'])
    op.drop_column('collected_data', 'collection_instance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collected_data', sa.Column('collection_instance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collected_data', type_='foreignkey')
    op.create_foreign_key('collected_data_collection_instance_fkey', 'collected_data', 'collection_instance', ['collection_instance'], ['id'])
    op.drop_column('collected_data', 'collection_instance_id')
    # ### end Alembic commands ###
