"""Adding not null to CollectedData and CollectionInstance tables

Revision ID: 89890b8ee28b
Revises: 0c0688bdb6ab
Create Date: 2021-07-03 02:23:38.294270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89890b8ee28b'
down_revision = '0c0688bdb6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collected_data', 'channel_1',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_2',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_3',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_4',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_5',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_6',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_7',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'channel_8',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('collected_data', 'is_subject_anxious',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('collected_data', 'collection_instance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collected_data', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collection_instance', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collection_instance', 'collection_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('collection_instance', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_instance', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collection_instance', 'collection_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('collection_instance', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collected_data', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collected_data', 'collection_instance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collected_data', 'is_subject_anxious',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('collected_data', 'channel_8',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_7',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_6',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_5',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_4',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_3',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_2',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('collected_data', 'channel_1',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
